'use client'
import type { Metadata } from "next";
import { Inter, Chakra_Petch } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/navbar";
import Register from "@/components/onboarding";
import Footer from "@/components/footer";
import AboutUs from "@/components/about";
import Script from "next/script";
import { useEffect } from "react";
import FAQPage from "@/components/faq";
import Timeline from "@/components/timeline";

const inter = Inter({ subsets: ["latin"] });
const chakra = Chakra_Petch({
  subsets: ["latin"] , 
  weight: "400",
  variable: "--font-chakra"
});

const kleemax = localfont({
  src : [{
    path: "../public/fonts/kleemaxdemo.ttf",
    weight : "400"
    }],
    variable: "--font-kleemax"
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Function to set the font size based on the parent's width and the number in the class name
    const setFontSizeForTextScaleElements = (): void => {
        // Select all elements whose class contains "text-scale-number"
        const elements = document.querySelectorAll<HTMLElement>('[class*="text-scale"]');

        // Iterate over each selected element
        elements.forEach(element => {
            // Get the parent element's width
            const parentElement = element.parentElement;

            // Ensure parentElement exists before proceeding
            if (parentElement) {
                const parentWidth = parentElement.clientWidth;

                // Extract the multiplier number from the class name
                const className = Array.from(element.classList).find(cls => cls.startsWith('text-scale'));
                const scaleNumberMatch = className?.match(/text-scale-(\d+(\.\d+)?)/);
                
                if (scaleNumberMatch) {
                    const scaleNumber = parseFloat(scaleNumberMatch[1]);

                    // Set the font size to parent's width multiplied by the extracted number
                    element.style.fontSize = `${parentWidth * scaleNumber/1000}px`;
                }
            }
        });
    };

    // Set the initial font size for all matching elements
    setFontSizeForTextScaleElements();

    // Adjust the font size when the window is resized
    window.addEventListener('resize', setFontSizeForTextScaleElements);

    // Clean up event listener on unmount
    return () => {
        window.removeEventListener('resize', setFontSizeForTextScaleElements);
    };
}, []);
  return (
    <html lang="en" className="bg-black">
      <body className={`${kleemax.variable} ${chakra.variable} bg-black`}>
        <Navbar/>
        <Register/>
        <AboutUs/>
        <Timeline/>
        <FAQPage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
